name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gnupg
      - name: Make executeable
        run: chmod +x .github/secrets/decrypt_secrets.sh 
             .github/scripts/archive_app.sh 
             .github/scripts/export_ipa.sh 
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run:  ./.github/secrets/decrypt_secrets.sh
      - name: Archiving project
        run: ./.github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Artifacts 
          path: ./artifacts
     
